---
- hosts: web
  become: true
  gather_facts: true
  vars:
    document_root: /www
  tasks:
    - name: "install httpd"
      ansible.builtin.package:
        name: "httpd"
        state: present
        update_cache: true
    - name: enable and start httpd
      ansible.builtin.service:
        name: "httpd"
        state: "started"
        enabled: "true"
    - name: create /www/html
      ansible.builtin.file:
        path: /www/html
        mode: 0755
        owner: apache
        group: apache
        state: directory
    - name: copy apache config
      ansible.builtin.template:
        src: httpd.conf.j2
        dest: /etc/httpd/conf/httpd.conf
        mode: 0644
        owner: apache
        group: apache
        backup: true
      notify:
        - restart-httpd
    - name: copy index.html
      ansible.builtin.template:
        src: index.html.j2
        dest: /www/html/index.html
        mode: 0644
        owner: apache
        group: apache
  handlers:
    - name: restart-httpd
      ansible.builtin.service:
        name: httpd
        state: restarted

